/**
 * Runtime generation of the two configuration files the application shell
 * loads: `config.js` (Jitsi client configuration) and `interface_config.js`
 * (branding/UI configuration).
 *
 * A deployment configures the backend through the environment, never through a
 * tracked file, so the same build can be pointed at a different signalling
 * deployment without a rebuild.
 */

const fs = require('fs');
const path = require('path');

/**
 * Signalling deployment used when the environment does not name one.
 */
const DEFAULT_BACKEND = 'alpha.jitsi.net';

/**
 * Hostnames we accept from the environment: dot separated labels with an
 * optional port. An allowlist, because the value is interpolated into the
 * JavaScript we serve to every visitor.
 */
const BACKEND_PATTERN = /^[a-z\d]([a-z\d-]*[a-z\d])?(\.[a-z\d]([a-z\d-]*[a-z\d])?)*(:\d{1,5})?$/i;

/**
 * Reads the signalling backend host from the environment.
 *
 * Accepts a bare host (`meet.example.com`) or a URL (`https://meet.example.com/`)
 * and always returns the bare host, because the host is what the client
 * configuration needs for the XMPP domain.
 *
 * @param {Object} env - The environment to read from.
 * @returns {string} The validated backend host.
 */
function readBackend(env) {
    const raw = String(env.MEETSPACE_BACKEND || DEFAULT_BACKEND).trim();
    const host = raw
        .replace(/^[a-z][a-z\d+.-]*:\/\//i, '')
        .replace(/\/.*$/, '');

    if (!BACKEND_PATTERN.test(host)) {
        throw new Error(
            `MEETSPACE_BACKEND is not a valid host: ${JSON.stringify(raw)}. `
            + 'Expected something like "meet.example.com".');
    }

    return host;
}

/**
 * Builds the client configuration object for a backend host.
 *
 * @param {string} backend - The signalling deployment host.
 * @returns {Object} The `config` object the application reads.
 */
function buildConfig(backend) {
    return {
        analytics: {
            disabled: true,
            rtcstatsEnabled: false
        },

        // Absolute URLs: this server serves the application only, it is not a
        // reverse proxy in front of the signalling deployment.
        bosh: `https://${backend}/http-bind`,
        websocket: `wss://${backend}/xmpp-websocket`,

        defaultLocalDisplayName: 'me',
        defaultRemoteDisplayName: 'Guest',

        deploymentInfo: {
            environment: 'meetspace'
        },

        // No gravatar, no analytics, no third party beacons.
        disableThirdPartyRequests: true,

        enableClosePage: false,

        // Visitors land on the welcome page and pick a room from there.
        enableWelcomePage: true,

        hosts: {
            domain: backend,
            muc: `conference.${backend}`
        },

        p2p: {
            enabled: true
        },

        // The prejoin screen shows the camera and microphone preview before
        // anything is joined.
        prejoinConfig: {
            enabled: true,
            hideDisplayName: false
        },

        testing: {}
    };
}

/**
 * Generates the `config.js` served to the browser.
 *
 * @param {Object} env - The environment to read the backend from.
 * @returns {string} JavaScript source declaring the global `config`.
 */
function buildConfigJs(env) {
    const backend = readBackend(env);
    const config = JSON.stringify(buildConfig(backend), null, 4);

    return '/* Generated by server/index.js. Configure with MEETSPACE_BACKEND. */\n'
        + `var config = ${config};\n`;
}

/**
 * Generates the `interface_config.js` served to the browser.
 *
 * The checked in file is the source of truth; the environment may only
 * override the application name, so a deployment can be renamed without a
 * rebuild.
 *
 * @param {Object} options - The options.
 * @param {Object} options.env - The environment to read overrides from.
 * @param {string} options.root - The repository root.
 * @returns {string} JavaScript source declaring the global `interfaceConfig`.
 */
function buildInterfaceConfigJs({ env, root }) {
    const source = fs.readFileSync(path.join(root, 'interface_config.js'), 'utf8');
    const appName = env.MEETSPACE_APP_NAME && String(env.MEETSPACE_APP_NAME).trim();

    if (!appName) {
        return source;
    }

    return `${source}\ninterfaceConfig.APP_NAME = ${JSON.stringify(appName)};\n`;
}

module.exports = {
    DEFAULT_BACKEND,
    buildConfigJs,
    buildInterfaceConfigJs,
    readBackend
};
