/* eslint-disable no-console */

/**
 * MeetSpace static demo server.
 *
 * Serves the prebuilt app (libs/, css/, images/, lang/, sounds/, static/,
 * demo/) plus the demo shell generated by demo/build-static.js, and proxies the
 * signalling paths (/http-bind, /xmpp-websocket, /colibri-ws) to
 * MEETSPACE_BACKEND so the browser stays on one origin. Node builtins only.
 *
 * PORT (or --port N) selects the port; binds 0.0.0.0.
 */

const fs = require('fs');
const http = require('http');
const https = require('https');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SHELL = path.join(ROOT, 'demo/index.static.html');
const BACKEND = process.env.MEETSPACE_BACKEND || 'alpha.jitsi.net';
const PORT = Number(process.env.PORT || (process.argv.indexOf('--port') !== -1
    ? process.argv[process.argv.indexOf('--port') + 1] : 8080));
const HOST = process.env.HOST || '0.0.0.0';

const STATIC_DIRS = new Set([ 'libs', 'css', 'images', 'lang', 'sounds', 'fonts', 'static', 'demo' ]);
const ROOT_FILES = new Set([ 'manifest.json', 'pwa-worker.js', 'favicon.ico', 'robots.txt' ]);
const TYPES = {
    '.html': 'text/html; charset=utf-8',
    '.js': 'text/javascript; charset=utf-8',
    '.mjs': 'text/javascript; charset=utf-8',
    '.css': 'text/css; charset=utf-8',
    '.json': 'application/json; charset=utf-8',
    '.map': 'application/json',
    '.wasm': 'application/wasm',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.gif': 'image/gif',
    '.svg': 'image/svg+xml',
    '.ico': 'image/x-icon',
    '.webp': 'image/webp',
    '.mp3': 'audio/mpeg',
    '.wav': 'audio/wav',
    '.ogg': 'audio/ogg',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
    '.ttf': 'font/ttf',
    '.txt': 'text/plain; charset=utf-8',
    '.bin': 'application/octet-stream'
};

function isProxied(url) {
    return url.startsWith('/http-bind') || url.startsWith('/xmpp-websocket') || url.startsWith('/colibri-ws');
}

function proxy(req, res) {
    const upstream = https.request({
        host: BACKEND,
        port: 443,
        method: req.method,
        path: req.url,
        headers: { ...req.headers, host: BACKEND }
    }, upstreamRes => {
        res.writeHead(upstreamRes.statusCode, upstreamRes.headers);
        upstreamRes.pipe(res);
    });

    upstream.on('error', err => {
        res.writeHead(502, { 'Content-Type': 'text/plain' });
        res.end(`backend ${BACKEND} unreachable: ${err.message}`);
    });
    req.pipe(upstream);
}

function sendFile(file, res) {
    fs.stat(file, (err, st) => {
        if (err || !st.isFile()) {
            res.writeHead(404, { 'Content-Type': 'text/plain' });

            return res.end('not found');
        }
        res.writeHead(200, {
            'Content-Type': TYPES[path.extname(file).toLowerCase()] || 'application/octet-stream',
            'Content-Length': st.size,
            // The shell and demo config change per deploy; the hashed-by-version libs can be cached.
            'Cache-Control': file === SHELL || file.startsWith(path.join(ROOT, 'demo'))
                ? 'no-store' : 'public, max-age=3600'
        });
        fs.createReadStream(file).pipe(res);
    });
}

const server = http.createServer((req, res) => {
    const url = decodeURIComponent((req.url || '/').split('?')[0]);

    if (isProxied(url)) {
        return proxy(req, res);
    }

    const rel = path.normalize(url).replace(/^(\.\.[/\\])+/, '').replace(/^\//, '');
    const first = rel.split('/')[0];

    if (rel === 'healthz') {
        res.writeHead(200, { 'Content-Type': 'text/plain' });

        return res.end('ok');
    }
    if (STATIC_DIRS.has(first) || ROOT_FILES.has(rel)) {
        return sendFile(path.join(ROOT, rel), res);
    }

    // `/` and `/RoomName` (no extension) load the app shell; anything else is 404.
    if (rel === '' || !path.extname(rel)) {
        return sendFile(SHELL, res);
    }

    res.writeHead(404, { 'Content-Type': 'text/plain' });
    res.end('not found');
});

// XMPP over websocket arrives as an HTTP upgrade — tunnel it to the backend.
server.on('upgrade', (req, socket, head) => {
    if (!isProxied(req.url || '')) {
        return socket.destroy();
    }
    const upstream = https.request({
        host: BACKEND,
        port: 443,
        method: req.method,
        path: req.url,
        headers: { ...req.headers, host: BACKEND }
    });

    upstream.on('upgrade', (upstreamRes, upstreamSocket, upstreamHead) => {
        const headers = Object.entries(upstreamRes.headers).map(([ k, v ]) => `${k}: ${v}`).join('\r\n');

        socket.write(`HTTP/1.1 101 Switching Protocols\r\n${headers}\r\n\r\n`);
        if (upstreamHead && upstreamHead.length) {
            upstreamSocket.unshift(upstreamHead);
        }
        upstreamSocket.pipe(socket);
        socket.pipe(upstreamSocket);
    });
    upstream.on('error', () => socket.destroy());
    socket.on('error', () => upstream.destroy());
    if (head && head.length) {
        req.unshift(head);
    }
    upstream.end();
});

server.listen(PORT, HOST, () => {
    console.log(`[meetspace] static demo on ${HOST}:${PORT}, signalling → ${BACKEND}`);
});
